#cloud-config
hostname: rancher-vmware-01

rancher:
  services_include:
    open-vm-tools: true
  network:
    interfaces:
      eth0:
       address: 192.168.199.100/24
       gateway: 192.168.199.254
       dhcp: false
    dns:
     nameservers:
      - 192.168.199.254

ssh_authorized_keys:
  - ssh-rsa ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAhcbiqRJGHH6ECQRAEVGrl/JALDQkbQl+43iODQOvVbMF16gu8oQdQfcliQPKb61Sv5ar8bZS1IJh0vN2BO3tocSXdRRZ7oQBrbTh1DCrSAuUVp2CrOYdRFQcoaHUaMPvn480zyMSISbid4OymCRJjoq0dk1iG9mRgGyHqY5Wn04VZaYmEaFOgiJP1OnPBXQH